/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ajudaqui.gestor360_api.kafka.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class BudgetItems extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6344628625978161055L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BudgetItems\",\"namespace\":\"com.ajudaqui.gestor360_api.kafka.entity\",\"fields\":[{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"BudgetItem\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"brand\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"double\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BudgetItems> ENCODER =
      new BinaryMessageEncoder<BudgetItems>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BudgetItems> DECODER =
      new BinaryMessageDecoder<BudgetItems>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<BudgetItems> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<BudgetItems> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BudgetItems>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this BudgetItems to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a BudgetItems from a ByteBuffer. */
  public static BudgetItems fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<com.ajudaqui.gestor360_api.kafka.entity.BudgetItem> items;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BudgetItems() {}

  /**
   * All-args constructor.
   * @param items The new value for items
   */
  public BudgetItems(java.util.List<com.ajudaqui.gestor360_api.kafka.entity.BudgetItem> items) {
    this.items = items;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return items;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: items = (java.util.List<com.ajudaqui.gestor360_api.kafka.entity.BudgetItem>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'items' field.
   * @return The value of the 'items' field.
   */
  public java.util.List<com.ajudaqui.gestor360_api.kafka.entity.BudgetItem> getItems() {
    return items;
  }

  /**
   * Sets the value of the 'items' field.
   * @param value the value to set.
   */
  public void setItems(java.util.List<com.ajudaqui.gestor360_api.kafka.entity.BudgetItem> value) {
    this.items = value;
  }

  /**
   * Creates a new BudgetItems RecordBuilder.
   * @return A new BudgetItems RecordBuilder
   */
  public static com.ajudaqui.gestor360_api.kafka.entity.BudgetItems.Builder newBuilder() {
    return new com.ajudaqui.gestor360_api.kafka.entity.BudgetItems.Builder();
  }

  /**
   * Creates a new BudgetItems RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BudgetItems RecordBuilder
   */
  public static com.ajudaqui.gestor360_api.kafka.entity.BudgetItems.Builder newBuilder(com.ajudaqui.gestor360_api.kafka.entity.BudgetItems.Builder other) {
    return new com.ajudaqui.gestor360_api.kafka.entity.BudgetItems.Builder(other);
  }

  /**
   * Creates a new BudgetItems RecordBuilder by copying an existing BudgetItems instance.
   * @param other The existing instance to copy.
   * @return A new BudgetItems RecordBuilder
   */
  public static com.ajudaqui.gestor360_api.kafka.entity.BudgetItems.Builder newBuilder(com.ajudaqui.gestor360_api.kafka.entity.BudgetItems other) {
    return new com.ajudaqui.gestor360_api.kafka.entity.BudgetItems.Builder(other);
  }

  /**
   * RecordBuilder for BudgetItems instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BudgetItems>
    implements org.apache.avro.data.RecordBuilder<BudgetItems> {

    private java.util.List<com.ajudaqui.gestor360_api.kafka.entity.BudgetItem> items;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ajudaqui.gestor360_api.kafka.entity.BudgetItems.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.items)) {
        this.items = data().deepCopy(fields()[0].schema(), other.items);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BudgetItems instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ajudaqui.gestor360_api.kafka.entity.BudgetItems other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.items)) {
        this.items = data().deepCopy(fields()[0].schema(), other.items);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'items' field.
      * @return The value.
      */
    public java.util.List<com.ajudaqui.gestor360_api.kafka.entity.BudgetItem> getItems() {
      return items;
    }

    /**
      * Sets the value of the 'items' field.
      * @param value The value of 'items'.
      * @return This builder.
      */
    public com.ajudaqui.gestor360_api.kafka.entity.BudgetItems.Builder setItems(java.util.List<com.ajudaqui.gestor360_api.kafka.entity.BudgetItem> value) {
      validate(fields()[0], value);
      this.items = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'items' field has been set.
      * @return True if the 'items' field has been set, false otherwise.
      */
    public boolean hasItems() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'items' field.
      * @return This builder.
      */
    public com.ajudaqui.gestor360_api.kafka.entity.BudgetItems.Builder clearItems() {
      items = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BudgetItems build() {
      try {
        BudgetItems record = new BudgetItems();
        record.items = fieldSetFlags()[0] ? this.items : (java.util.List<com.ajudaqui.gestor360_api.kafka.entity.BudgetItem>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BudgetItems>
    WRITER$ = (org.apache.avro.io.DatumWriter<BudgetItems>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BudgetItems>
    READER$ = (org.apache.avro.io.DatumReader<BudgetItems>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
